import { useState } from 'react';
import { Gift, SlidersHorizontal, ArrowRight, Check, Leaf } from 'lucide-react';
import { combos,products,money } from '../catalog';
import { ProduceImage } from '../components/ProductCard';
export default function Combos({onAdd,onInfo}:{onAdd:(s:string)=>void;onInfo:(s:string)=>void}){
 const [selected,setSelected]=useState<string[]>([]);
 const total=products.filter(p=>selected.includes(p.id)).reduce((s,p)=>s+p.price,0);
 return <><section className="combo-hero"><div className="page-container two-column"><div><span className="eyebrow">Mua thông minh · Ăn ngon · Cứu nhiều hơn</span><h1>Combo & <em>Túi mù</em><br/>từ mùa vụ hôm nay.</h1><p>Tiết kiệm nhiều hơn khi mua theo gói, nhận đủ rau củ tươi theo mùa và đón một giỏ bất ngờ cho gia đình bạn.</p><div className="button-row"><a href="#/combo-tui-mu/goi-combo" className="btn btn-gold">Khám phá combo<ArrowRight size={17}/></a><a href="#/quy-trinh" className="btn btn-light-outline">Xem cách hoạt động</a></div></div><ProduceImage src={combos[0].image} alt="Mùa vụ tươi ngon từ nông dân Việt Nam" className="page-hero-image"/></div></section>
 <section className="section-pad"><div className="page-container"><div className="breadcrumb"><a href="#/">Trang chủ</a><span>›</span>Combo & Túi mù</div><div className="mystery-box"><div><span className="pill"><Gift size={14}/>Bất ngờ từ mùa vụ</span><h2>Túi mù nông sản<br/>(Mystery Box)</h2><p>Nhận 5kg rau củ quả ngẫu nhiên theo mùa từ các nhà vườn liên kết. Thành phần thay đổi theo ngày; bạn không chọn từng loại trong túi.</p><div className="mystery-price">79.000đ <small>/ túi 5kg</small></div><button className="btn btn-green" onClick={()=>onAdd('mystery')}><Gift size={19}/>Thêm túi mù 79k</button></div><ProduceImage src={products[1].image} alt="Rau củ theo mùa trong túi mù" className="mystery-image"/></div>
 <div id="goi-combo" className="section-heading mt-12"><div><span className="eyebrow">Một giỏ ngon, nhiều niềm vui</span><h2>Chọn cách bạn muốn giải cứu</h2><p>Lựa chọn linh hoạt cho nhịp sống và ngân sách của bạn.</p></div></div><div className="combo-cards">{[combos[1],null,combos[2]].map((p,index)=><article key={index}><ProduceImage src={p?.image||products[3].image} alt={p?.name||'Combo cá nhân'}/><div className="combo-card-content"><span className="pill">{['Ăn xanh cả tuần','Chọn món yêu thích','Cho quán ăn & bếp'][index]}</span><h3>{p?.name||'Build Combo cá nhân tuần'}</h3><p>{['Rau củ và gia vị tươi cho gia đình 2–3 người, đơn giản hóa chuyện đi chợ mỗi ngày.','Tự chọn từng loại nông sản bên dưới. Giá giỏ được tính theo số món bạn chọn.','Giỏ nguyên liệu 10kg cho bếp chay, quán ăn và người chuẩn bị bữa ăn cả tuần.'][index]}</p><strong>{p?money(p.price):'Tùy chọn theo ngân sách'}</strong>{p?<button className="btn btn-green" onClick={()=>onAdd(p.id)}>Thêm combo vào giỏ</button>:<a href="#/combo-tui-mu/tao-combo" className="btn btn-green"><SlidersHorizontal size={17}/>Tự thiết kế combo</a>}</div></article>)}</div>
 <section className="combo-builder" id="tao-combo"><div><span className="eyebrow">Giỏ của bạn, theo ý bạn</span><h2>Tự chọn nông sản cho tuần mới</h2><p>Mỗi món được chọn tương ứng 1kg. Có thể điều chỉnh số lượng trong giỏ hàng.</p></div><div className="builder-options">{products.map(p=><button key={p.id} aria-pressed={selected.includes(p.id)} className={selected.includes(p.id)?'chosen':''} onClick={()=>setSelected(s=>s.includes(p.id)?s.filter(id=>id!==p.id):[...s,p.id])}><ProduceImage src={p.image} alt={p.name}/><span>{p.name}<strong>{money(p.price)}/kg</strong></span>{selected.includes(p.id)?<Check size={20}/>:<span className="unchecked"/>}</button>)}</div><div className="builder-total"><div><span>{selected.length} món đã chọn</span><strong>{money(total)}</strong></div><button className="btn btn-green" disabled={!selected.length} onClick={()=>{selected.forEach(onAdd);setSelected([]);}}>Thêm giỏ đã chọn</button></div></section>
 <div className="callout"><div><h2>Rủ bạn cùng giải cứu</h2><p>Cùng chia sẻ những bữa ăn xanh và câu chuyện từ nhà vườn.</p></div><button className="btn btn-gold" onClick={()=>onInfo('Chương trình giới thiệu bạn bè')}>Khám phá chương trình<ArrowRight size={17}/></button></div><div className="benefit-grid">{['Mỗi túi một bất ngờ','Nông sản theo mùa','Đóng gói thân thiện'].map(t=><div key={t}><Leaf/><h3>{t}</h3><p>Trân trọng mùa vụ, mang vị tươi ngon từ vườn đến bàn ăn.</p></div>)}</div></div></section></>;
}
