import { Search, SlidersHorizontal, Leaf, MapPin, Truck, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { filterProducts, products } from '../catalog';
import ProductCard,{ProduceImage} from '../components/ProductCard';
export default function Fresh({query,setQuery,onAdd,onInfo}:{query:string;setQuery:(s:string)=>void;onAdd:(s:string)=>void;onInfo:(s:string)=>void}){
 const [category,setCategory]=useState('Tất cả');const [sort,setSort]=useState('featured');
 const items=filterProducts(query,category,sort);
 return <><div className="page-container breadcrumb"><a href="#/">Trang chủ</a><span>›</span>Nông sản tươi</div><section className="fresh-hero"><div className="page-container two-column"><div><span className="eyebrow">Chợ nông sản giải cứu · Thu hoạch trong ngày</span><h1>Đẹp theo cách<br/><em>tự nhiên nhất.</em></h1><p>Những củ cà rốt hai nhánh, quả cà chua lệch size hay trái cây rám nắng vẫn giữ trọn vị ngon và dinh dưỡng. Mua trực tiếp từ vườn, giá tốt hơn 30–50%.</p><div className="button-row"><a className="btn btn-gold" href="#/nong-san-tuoi/san-pham">Khám phá nông sản</a><button className="btn btn-outline" onClick={()=>onInfo('Tìm bằng ảnh AI')}><Sparkles size={17}/>Tìm bằng ảnh</button></div></div><ProduceImage src={products[0].image} alt="Nông sản mộc mạc từ nhà vườn" className="page-hero-image"/></div></section>
 <section className="section-pad" id="san-pham"><div className="page-container"><div className="section-heading"><div><h2>Nông sản tươi hôm nay</h2><p>{items.length} sản phẩm phù hợp · Giá và điểm AI minh họa</p></div><label className="sort-control"><SlidersHorizontal size={16}/><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sắp xếp sản phẩm"><option value="featured">Nổi bật</option><option value="price-asc">Giá thấp đến cao</option><option value="price-desc">Giá cao đến thấp</option><option value="stock">Còn ít hàng</option></select></label></div>
 <label className="catalog-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm theo tên, nhà vườn hoặc vùng trồng..." aria-label="Lọc nông sản"/></label><div className="filter-chips" aria-label="Danh mục nông sản">{['Tất cả','Rau ăn lá','Củ quả','Trái cây','Hữu cơ','Đà Lạt'].map(c=><button key={c} aria-pressed={category===c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 {items.length?<div className="product-grid">{items.map(p=><ProductCard key={p.id} product={p} onAdd={onAdd}/>)}</div>:<div className="empty-state"><Leaf size={40}/><h3>Chưa có nông sản phù hợp</h3><p>Thử từ khóa khác hoặc xem lại tất cả sản phẩm.</p><button className="btn btn-green" onClick={()=>{setQuery('');setCategory('Tất cả');}}>Xóa bộ lọc</button></div>}
 <div className="callout"><div><h2>Không biết chọn gì cho bữa tối?</h2><p>Khám phá cách AI gợi ý nông sản phù hợp cho gia đình.</p></div><button className="btn btn-gold" onClick={()=>onInfo('AI gợi ý thực đơn')}><Sparkles size={17}/>AI chọn giúp tôi</button></div><div className="benefit-grid">{[[Leaf,'AI kiểm định dinh dưỡng','Thông tin chất lượng và điểm độ tươi được trình bày ngay trên sản phẩm.'],[MapPin,'Thẳng từ nhà vườn','Biết rõ ai trồng, vùng trồng và từng câu chuyện mùa vụ.'],[Truck,'Giao trong 2–4 giờ','Thiết kế cho trải nghiệm giao nhanh và đóng gói thân thiện.']].map(([Icon,title,copy])=>{const I=Icon as typeof Leaf;return <div key={String(title)}><I/><h3>{String(title)}</h3><p>{String(copy)}</p></div>;})}</div></div></section></>;
}
